version: "3"
services:
    client:
        build: client
        ports:
            - 300:3000
        depends_on:
            - server
    server:
        build: server
        ports:
            - 443:443